# Fluxo de trabalho para gerar e atualizar dados

name: Gerar Dados

on:
  # Executar a cada 12 horas
  schedule:
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  generate-data:
    name: Gerar dados e atualizar repositório
    runs-on: ubuntu-latest
    steps:
      # Gerar animação da cobra
      - name: Gerar animação da cobra
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: Thiago-Cruz-Esteves
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Publicar atualizações no GitHub Pages
      - name: Publicar atualizações no GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# Comentários explicando o que cada etapa faz
# A etapa "Gerar animação da cobra" usa o pacote Platane/snk para gerar uma animação da grade de contribuição do usuário do GitHub.
# A etapa "Publicar atualizações no GitHub Pages" usa o pacote crazy-max/ghaction-github-pages para publicar as atualizações no GitHub Pages.
# O token de acesso do GitHub é passado para a etapa "Publicar atualizações no GitHub Pages" usando a variável secrets.GITHUB_TOKEN. Isso permite que a ação publique as atualizações no repositório. 
